google:
  - api_key: "AIzaSyCdc-wtEBD3nHwbrNIyvh96M28hKrZE2w8"
    search_engine_id: "528bf601158584f50"
  - api_key: "AIzaSyBLaVks8zlv3Uq5rWllk-2X7D8GZ8q3wlc"
    search_engine_id: "c45368a5346b7498e"
  - api_key: "AIzaSyCudRywZpRdl8n-5uJy-Oxnsb1AoNK_To4"
    search_engine_id: "16d240269f69446cd"
  - api_key: "AIzaSyA6_8yWhfryi_e56Lw_XjBVvZeYV2-vFrc"
    search_engine_id: "b406604df837648d1"
  - api_key: "AIzaSyD80WDvxH115bWDrEe0mAZPbizPiZzNA3s"
    search_engine_id: "11abad680bfca4ef7"
